### ISSUE TITLE
Cannot create Production Build

### ISSUE THREAD

**Issue by chamow97** [chamow97/vxslift#7]
When I try to do the production build, I get an error.. It used to work in the basic version of the application. 

Seems like we are mixing SSR and CSR flow in NextJS app. Can you look into this issue? Its blocking me from deploying the application. 

 

 

Steps to reproduce: 

 

1. Clone the VXSLift application

2. Run npm run build

3. See that the build fails due to "window" variable being used. 

 

Requesting you to look into the same.

**Comment by chamow97** [comment]
Stack Trace
```
[next-auth][error][SIGNIN_OAUTH_ERROR]
https://next-auth.js.org/errors#signin_oauth_error client_id is required {
  error: {
    message: 'client_id is required',
    stack: 'TypeError: client_id is required\n' +
      '    at new BaseClient (webpack-internal:///(rsc)/./node_modules/openid-client/lib/client.js:148:19)\n' +
      '    at new Client (webpack-internal:///(rsc)/./node_modules/openid-client/lib/client.js:1673:13)\n' +
      '    at openidClient (webpack-internal:///(rsc)/./node_modules/next-auth/core/lib/oauth/client.js:23:20)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
      '    at async getAuthorizationUrl (webpack-internal:///(rsc)/./node_modules/next-auth/core/lib/oauth/authorization-url.js:72:20)\n' +
      '    at async Object.signin (webpack-internal:///(rsc)/./node_modules/next-auth/core/routes/signin.js:21:30)\n' +
      '    at async AuthHandler (webpack-internal:///(rsc)/./node_modules/next-auth/core/index.js:243:36)\n' +
      '    at async NextAuthRouteHandler (webpack-internal:///(rsc)/./node_modules/next-auth/next/index.js:50:30)\n' +
      '    at async NextAuth._args$ (webpack-internal:///(rsc)/./node_modules/next-auth/next/index.js:85:24)\n' +
      '    at async /Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:63809\n' +
      '    at async eU.execute (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:53964)\n' +
      '    at async eU.handle (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:65062)\n' +
      '    at async doRender (/Users/mowlij/proj/vxslift/node_modules/next/dist/server/base-server.js:1333:42)\n' +
      '    at async cacheEntry.responseCache.get.routeKind (/Users/mowlij/proj/vxslift/node_modules/next/dist/server/base-server.js:1543:40)\n' +
      '    at async DevServer.renderToResponseWithComponentsImpl (/Users/mowlij/proj/vxslift/node_modules/next/dist/server/base-server.js:1463:28)\n' +
      '    at async DevServer.renderPageComponent (/Users/mowlij/proj/vxslift/node_modules/next/dist/server/base-server.js:1856:24)\n' +
      '    at async DevServer.renderToResponseImpl (/Users/mowlij/proj/vxslift/node_modules/next/dist/server/base-server.js:1894:32)\n' +
      '    at async DevServer.pipeImpl (/Users/mowlij/proj/vxslift/node_modules/next/dist/server/base-server.js:911:25)\n' +
      '    at async NextNodeServer.handleCatchallRenderRequest (/Users/mowlij/proj/vxslift/node_modules/next/dist/server/next-server.js:271:17)\n' +
      '    at async DevServer.handleRequestImpl (/Users/mowlij/proj/vxslift/node_modules/next/dist/server/base-server.js:807:17)\n' +
      '    at async /Users/mowlij/proj/vxslift/node_modules/next/dist/server/dev/next-dev-server.js:331:20\n' +
      '    at async Span.traceAsyncFn (/Users/mowlij/proj/vxslift/node_modules/next/dist/trace/trace.js:151:20)\n' +
      '    at async DevServer.handleRequest (/Users/mowlij/proj/vxslift/node_modules/next/dist/server/dev/next-dev-server.js:328:24)\n' +
      '    at async invokeRender (/Users/mowlij/proj/vxslift/node_modules/next/dist/server/lib/router-server.js:163:21)\n' +
      '    at async handleRequest (/Users/mowlij/proj/vxslift/node_modules/next/dist/server/lib/router-server.js:342:24)\n' +
      '    at async requestHandlerImpl (/Users/mowlij/proj/vxslift/node_modules/next/dist/server/lib/router-server.js:366:13)\n' +
      '    at async Server.requestListener (/Users/mowlij/proj/vxslift/node_modules/next/dist/server/lib/start-server.js:140:13)',
    name: 'TypeError'
  },
  providerId: 'google',
  message: 'client_id is required'
}
 ⨯ src/components/Header/index.tsx (145:36) @ window
 ⨯ ReferenceError: window is not defined
    at eval (./src/components/Header/index.tsx:176:105)
    at Array.map (<anonymous>)
    at Header (./src/components/Header/index.tsx:172:103)
  143 |                                 pathName === "/"
  144 |                                   ? "black"
> 145 |                                   : window.innerWidth > 990
      |                                    ^
  146 |                                     ? "white"
  147 |                                     : "black",
  148 |                               fontWeight: "bolder",


^C
mowlij@bcd0743f3b30 vxslift %
mowlij@bcd0743f3b30 vxslift %
mowlij@bcd0743f3b30 vxslift %
mowlij@bcd0743f3b30 vxslift %
mowlij@bcd0743f3b30 vxslift % npm run build

> startup-nextjs-template@2.0.0 build
> next build

   ▲ Next.js 14.1.0

   Creating an optimized production build ...
 ✓ Compiled successfully
 ✓ Linting and checking validity of types
 ✓ Collecting page data
   Generating static pages (0/7)  [=   ]ReferenceError: window is not defined
    at /Users/mowlij/proj/vxslift/.next/server/chunks/209.js:1:9968
    at Array.map (<anonymous>)
    at u (/Users/mowlij/proj/vxslift/.next/server/chunks/209.js:1:9856)
    at nM (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47419)
    at nN (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64674)
    at nB (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67657)
    at nF (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:66824)
    at nN (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64990)
    at nB (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67657)
    at nF (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:66824)

Error occurred prerendering page "/signin". Read more: https://nextjs.org/docs/messages/prerender-error

ReferenceError: window is not defined
    at /Users/mowlij/proj/vxslift/.next/server/chunks/209.js:1:9968
    at Array.map (<anonymous>)
    at u (/Users/mowlij/proj/vxslift/.next/server/chunks/209.js:1:9856)
    at nM (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47419)
    at nN (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64674)
    at nB (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67657)
    at nF (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:66824)
    at nN (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64990)
    at nB (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67657)
    at nF (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:66824)
ReferenceError: window is not defined
    at /Users/mowlij/proj/vxslift/.next/server/chunks/209.js:1:9968
    at Array.map (<anonymous>)
    at u (/Users/mowlij/proj/vxslift/.next/server/chunks/209.js:1:9856)
    at nM (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47419)
    at nN (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64674)
    at nB (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67657)
    at nF (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:66824)
    at nN (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64990)
    at nB (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67657)
    at nF (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:66824)

Error occurred prerendering page "/my-account". Read more: https://nextjs.org/docs/messages/prerender-error

ReferenceError: window is not defined
    at /Users/mowlij/proj/vxslift/.next/server/chunks/209.js:1:9968
    at Array.map (<anonymous>)
    at u (/Users/mowlij/proj/vxslift/.next/server/chunks/209.js:1:9856)
    at nM (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47419)
    at nN (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64674)
    at nB (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67657)
    at nF (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:66824)
    at nN (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64990)
    at nB (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67657)
    at nF (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:66824)
ReferenceError: window is not defined
    at /Users/mowlij/proj/vxslift/.next/server/chunks/209.js:1:9968
    at Array.map (<anonymous>)
    at u (/Users/mowlij/proj/vxslift/.next/server/chunks/209.js:1:9856)
    at nM (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47419)
    at nN (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64674)
    at nB (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67657)
    at nF (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:66824)
    at nN (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64990)
    at nB (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67657)
    at nF (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:66824)
ReferenceError: window is not defined
    at /Users/mowlij/proj/vxslift/.next/server/chunks/209.js:1:9968
    at Array.map (<anonymous>)
    at u (/Users/mowlij/proj/vxslift/.next/server/chunks/209.js:1:9856)
    at nM (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47419)
    at nN (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64674)
    at nB (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67657)
    at nF (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:66824)
    at nN (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64990)
    at nB (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67657)
    at nF (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:66824)

Error occurred prerendering page "/signup". Read more: https://nextjs.org/docs/messages/prerender-error

ReferenceError: window is not defined
    at /Users/mowlij/proj/vxslift/.next/server/chunks/209.js:1:9968
    at Array.map (<anonymous>)
    at u (/Users/mowlij/proj/vxslift/.next/server/chunks/209.js:1:9856)
    at nM (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47419)
    at nN (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64674)
    at nB (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67657)
    at nF (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:66824)
    at nN (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64990)
    at nB (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67657)
    at nF (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:66824)

Error occurred prerendering page "/_not-found". Read more: https://nextjs.org/docs/messages/prerender-error

ReferenceError: window is not defined
    at /Users/mowlij/proj/vxslift/.next/server/chunks/209.js:1:9968
    at Array.map (<anonymous>)
    at u (/Users/mowlij/proj/vxslift/.next/server/chunks/209.js:1:9856)
    at nM (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47419)
    at nN (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64674)
    at nB (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67657)
    at nF (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:66824)
    at nN (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64990)
    at nB (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67657)
    at nF (/Users/mowlij/proj/vxslift/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:66824)
 ✓ Generating static pages (7/7)

> Export encountered errors on following paths:
	/_not-found
	/my-account/page: /my-account
	/signin/page: /signin
	/signup/page: /signup
```
